<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findNote($motclef)
    {
        $qb = $this->createQueryBuilder('m')
            ->leftJoin('m.responsable', 'u')
            ->leftJoin('m.students', 's')
            ->where("s.name LIKE :motclef OR s.login LIKE :motclef OR m.name LIKE :motclef OR m.code LIKE :motclef OR u.username LIKE :motclef " )
            ->setParameter('motclef', $motclef);

        return $qb->getQuery()
            ->getResult();
    }
}