<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findWithStudents($id)
    {
        $qb = $this->createQueryBuilder('m')
            ->addSelect('s')
            ->leftJoin('m.students', 's')
            ->where('s.id= :id')
            ->setParameter('id', $id);
        return $qb->getQuery()
            ->getResult();
    }
}