<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{

    public function findNote($motclef)
    {
        $qb = $this->createQueryBuilder('n')
            ->leftJoin('n.student', 's')
            ->leftJoin('n.module', 'm')
            ->where("s.name LIKE :motclef OR s.login LIKE :motclef OR m.name LIKE :motclef OR m.code LIKE :motclef" )
            ->setParameter('motclef', $motclef);

        return $qb->getQuery()
            ->getResult();
    }
}
