<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{

    public function findNote($motclef)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.student LIKE :string')
            ->orWhere('n.module LIKE :string')
            ->setParameter('string', $motclef);
        return $qb->getQuery()
            ->getResult();
    }
}
