<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewCenterRepository extends EntityRepository
{
}
