<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{

    public function findStudent($motclef)
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.modules', 'm')
            ->leftJoin('s.registerCenter', 'r')
            ->where("s.name LIKE :motclef OR s.login LIKE :motclef OR s.mail LIKE :motclef OR s.phone LIKE :motclef OR m.name LIKE :motclef OR m.code LIKE :motclef OR r.name LIKE :motclef" )
            ->setParameter('motclef', $motclef);

        return $qb->getQuery()
            ->getResult();
    }
}
