<?php

namespace Emiage\ReviewManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorRepository extends EntityRepository
{

    public function findTutor($motclef)
    {
        $qb = $this->createQueryBuilder('t')
            ->leftJoin('t.modules', 'm')
            ->leftJoin('t.user', 'u')
            ->where("m.name LIKE :motclef OR m.code LIKE :motclef OR u.username LIKE :motclef OR u.email LIKE :motclef" )
            ->setParameter('motclef', $motclef);

        return $qb->getQuery()
            ->getResult();
    }
}
