security:
    encoders:
        Emiage\UserBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_STUD:        ROLE_STUD
        ROLE_PROF:        ROLE_PROF
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_STUD, ROLE_PROF, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
         dev:
              pattern:  ^/(_(profiler|wdt)|css|images|js)/
              security: false
         main:
             pattern: ^/
             anonymous: true
             provider: main
             form_login:
                   login_path: fos_user_security_login
                   check_path: fos_user_security_check
             logout:
                   path: fos_user_security_logout
                   target: /
             remember_me:
                 key: %secret% # %secret% est un paramètre de parameters.yml

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/prof/, role: ROLE_PROF }
            - { path: ^/stud/, role: ROLE_STUD }
