examen:
    pattern:  /home/{page}
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:index", page: 1 }

examen_show:
    pattern:  /{id}/show
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:show" }

examen_new:
    pattern:  /new
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:new" }

examen_create:
    pattern:  /create
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:create" }
    requirements: { _method: post }

examen_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:edit" }

examen_update:
    pattern:  /{id}/update
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:update" }
    requirements: { _method: post|put }

examen_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EmiageReviewManagerBundle:Examen:delete" }

examen_inscription:
    pattern: /{id}/inscription
    defaults: {_controller: "EmiageReviewManagerBundle:Examen:inscription" }

examen_addStudent:
    pattern: /{id}/addStudent
    defaults: {_controller: "EmiageReviewManagerBundle:Examen:addStudent" }
