note:
    pattern:  /home/{page}
    defaults: { _controller: "EmiageReviewManagerBundle:Note:index", page: 1 }

note_student:
    pattern:  /home/{page}/{id}
    defaults: { _controller: "EmiageReviewManagerBundle:Note:indexStudent", page: 1 }

note_push_copy:
    pattern:  /home/{page}/{idc}/{idm}
    defaults: { _controller: "EmiageReviewManagerBundle:Note:pushCopy", page: 1 }

note_show:
    pattern:  /{id}/show
    defaults: { _controller: "EmiageReviewManagerBundle:Note:show" }

note_new:
    pattern:  /new
    defaults: { _controller: "EmiageReviewManagerBundle:Note:new" }

note_create:
    pattern:  /create
    defaults: { _controller: "EmiageReviewManagerBundle:Note:create" }
    requirements: { _method: post }

note_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EmiageReviewManagerBundle:Note:edit" }

note_update:
    pattern:  /{id}/update
    defaults: { _controller: "EmiageReviewManagerBundle:Note:update" }
    requirements: { _method: post|put }

note_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EmiageReviewManagerBundle:Note:delete" }

note_download:
    pattern: /{slug}/download
    defaults: { _controller: "EmiageReviewManagerBundle:Note:download" }

note_new_by_student:
    pattern: /{ide}/{idm}/addnote
    defaults: { _controller: "EmiageReviewManagerBundle:Note:addnote" }

