note:
    pattern:  /
    defaults: { _controller: "EmiageReviewManagerBundle:Note:index" }

note_show:
    pattern:  /{id}/show
    defaults: { _controller: "EmiageReviewManagerBundle:Note:show" }

note_new:
    pattern:  /new
    defaults: { _controller: "EmiageReviewManagerBundle:Note:new" }

note_create:
    pattern:  /create
    defaults: { _controller: "EmiageReviewManagerBundle:Note:create" }
    requirements: { _method: post }

note_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EmiageReviewManagerBundle:Note:edit" }

note_update:
    pattern:  /{id}/update
    defaults: { _controller: "EmiageReviewManagerBundle:Note:update" }
    requirements: { _method: post|put }

note_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EmiageReviewManagerBundle:Note:delete" }

note_download:
    pattern: /{slug}/download
    defaults: { _controller: "EmiageReviewManagerBundle:Note:download" }

note_research:
    pattern: /note/research
    defaults: { _controller: "EmiageReviewManagerBundle:Note:research" }
    requirements:
      _method: POST

note_upload:
    pattern: /{id}/upload
    defaults: { _controller: "EmiageReviewManagerBundle:Note:upload" }

