Emiage\ReviewManagerBundle\Entity\Module:
    properties:
        file:
            - File:
                mimeTypes: [application/rar, application/x-rar, application/x-rar-compressed, application/x-compressed, application/octet-stream]
                mimeTypesMessage: Choisissez un fichier en .rar