Emiage\ReviewManagerBundle\Entity\Module:
    properties:
        file:
            - File:
                mimeTypes: [application/rar, application/x-rar, application/x-rar-compressed, application/x-compressed, application/octet-stream]
                mimeTypesMessage: Choisissez un fichier en .rar

Emiage\ReviewManagerBundle\Entity\Note:
    properties:
        file:
            - File:
                mimeTypes: [application/rar, application/x-rar, application/x-rar-compressed, application/x-compressed, application/octet-stream, application/msword, image/tiff, image/jpeg, application/pdf]
                mimeTypesMessage: Choisissez un fichier en .rar .tiff .jpeg .doc ou .pdf