<?php

namespace Emiage\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findRoleProf()
    {
        $qb = $this->createQueryBuilder('u')
            ->where("u.roles = :motclef")
            ->setParameters('motclef', 'ROLE_PROF');

        return $qb->getQuery()
            ->getResult();
    }
}
